#%RAML 1.0 NamedExample
 #? is optional
value:
   FirstName?: George
   LastName?: Clooney
   Age?: 27
   Gender?: Male
   TypeofCustomer?: Frequent
   Revenue?: 20000
   Contact?: georgeclooney@gmail.com