#%RAML 1.0 NamedExample
value:
  CustomerID : 2
  BillingAddress1 : 24 - HighTown Road, Bermouth
  BillingAddress2 : 45B - HillTown, NY
  ShippingAddress : 65C - Neigh Road, Near Baltimore HW , CA
  City : Chennai
  State : Tamil Nadu
  Country : India
  PostalCode : 233423
  MobileNo : 5453545432
  AddressUpdatedAt : 2021-12-31 23:59:59