#%RAML 1.0 NamedExample
value:
  -
    OrderID: 2
    CustomerID: 106
    InvoiceID: 102
    InvoiceName: Raj & Son's Invoice
    ItemID: 40006
    ItemName: Axe Bottle Perfume
    Quantity: 3
    BasePrice: 100
    PromoCode: AB340
    TotalPrice: 300
    OrderCreatedAt: 2021-12-31 23:59:59
  
  -
    OrderID: 3
    CustomerID: 106
    InvoiceID: 102
    InvoiceName: Deckee & Son's Invoice
    ItemID: 40043
    ItemName: Nova Trimmer
    Quantity: 10
    BasePrice: 500
    PromoCode: AB342
    TotalPrice: 5000
    OrderCreatedAt: 2021-12-31 22:59:59