#%RAML 1.0 DataType

type: object
properties:
  #? is optional
  CustomerId?: integer
  FirstName?: string
  LastName?: string
  Age?: integer
  Gender?: string
  TypeofCustomer?: string
  Revenue?: integer
  Contact?: string